spring:
  application:
    name: umigoCrmBackend

  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      pool-name: HikariPool-1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: 
      port: 
      password: 
      database: 

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  config: classpath:log4j2.xml

umigo:
  firebase:
    config:
      path: 
  jwt:
    access-secret: 
    refresh-secret: 
    access-ttl: 
    refresh-ttl: 
