/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'pro-naive',
    path: '/pro-naive',
    component: 'layout.base',
    meta: {
      title: 'pro-naive',
      i18nKey: 'route.pro-naive',
      order: 7,
      icon: 'material-symbols-light:demography-outline-rounded'
    },
    children: [
      {
        name: 'pro-naive_form',
        path: '/pro-naive/form',
        meta: {
          title: 'pro-naive_form',
          i18nKey: 'route.pro-naive_form',
          icon: 'fluent:form-28-regular'
        },
        children: [
          {
            name: 'pro-naive_form_basic',
            path: '/pro-naive/form/basic',
            component: 'view.pro-naive_form_basic',
            meta: {
              title: 'pro-naive_form_basic',
              i18nKey: 'route.pro-naive_form_basic'
            }
          },
          {
            name: 'pro-naive_form_query',
            path: '/pro-naive/form/query',
            component: 'view.pro-naive_form_query',
            meta: {
              title: 'pro-naive_form_query',
              i18nKey: 'route.pro-naive_form_query'
            }
          },
          {
            name: 'pro-naive_form_step',
            path: '/pro-naive/form/step',
            component: 'view.pro-naive_form_step',
            meta: {
              title: 'pro-naive_form_step',
              i18nKey: 'route.pro-naive_form_step'
            }
          }
        ]
      },
      {
        name: 'pro-naive_table',
        path: '/pro-naive/table',
        meta: {
          title: 'pro-naive_table',
          i18nKey: 'route.pro-naive_table',
          icon: 'mynaui:table'
        },
        children: [
          {
            name: 'pro-naive_table_remote',
            path: '/pro-naive/table/remote',
            component: 'view.pro-naive_table_remote',
            meta: {
              title: 'pro-naive_table_remote',
              i18nKey: 'route.pro-naive_table_remote'
            }
          },
          {
            name: 'pro-naive_table_row-edit',
            path: '/pro-naive/table/row-edit',
            component: 'view.pro-naive_table_row-edit',
            meta: {
              title: 'pro-naive_table_row-edit',
              i18nKey: 'route.pro-naive_table_row-edit'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
