version: '3.9'

services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: umigo
      POSTGRES_PASSWORD: umigo
      POSTGRES_DB: umigo
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--databases"
      - "2"
      - "--requirepass"
      - "umigo"          # <-- Redis password requirement
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
    driver: local